### ISSUE TITLE
producer puts more messages into frame than is allowed by frame size

### ISSUE THREAD

**Issue by ddl-ssenecal** [rabbitmq/rabbitmq-stream-java-client#207]
I'm running into an issue where the Producer is batching more messages than will fit into a single frame, resulting in an inability to send messages.  The problem originates with the fact that I have 2 messages which are very large (900KB and 450KB) followed by a collection of very small messages (1-10KB).  What appears to be happening is that multiple messages are being batched together (expected), but its adding more messages than fit into the frame resulting in:

```
java.lang.IllegalArgumentException: Message too big to fit in one frame: 1583904
```

Looking at `StreamProducer.publishBatch()`, it doesn't appear to consider the max frame size while batching.  Is this intentional?  Is there some other way to control the number of messages included in a batch by size?  It seems like it would be trivial to add a "max batch bytes" parameter to the StreamProducer to allow users to control this, or even just using the max frame size directly.  It would get murkier if compression is enabled, but perhaps you could just limit based on the raw (uncompressed) bytes, and that would be good enough for most use cases.

Ideally, I would be able to keep batching messages up to "batch size", but it would also cut short if the batch would exceed the frame size, allowing me to batch as much as possible.

**Comment by acogoluegnes** [comment]
The frame size verification is done in the `Client` class, not in `StreamProducer` IIRC.

Could you provide a test case that reproduces the problem?

Thanks.

**Comment by ddl-ssenecal** [comment]
Sure.  Can I just extend `StreamProducerTest` to reproduce it?  Looks like that test requires a broker running on `localhost/127.0.0.1:5552`, is there a script somewhere I can run to set up that broker?

**Comment by ddl-ssenecal** [comment]
My bad, I see it documented in the README.

**Comment by ddl-ssenecal** [comment]
My apologies.  It seems that a single one of my encoded messages is larger than the frame size, resulting in this error.  After adding a test to `StreamProducerTest`, I was able to confirm that in fact the `Client` does validate the batch doesn't exceed the frame size and handles the situation as expected.

I'll close the issue now, as the issue is on my end.

**Comment by acogoluegnes** [comment]
OK, no worries, thanks for the follow-up.
